services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: node
    container_name: scratchpay-api
    restart: unless-stopped
    env_file: .env
    ports:
      - 3001:3000
    volumes:
      - .:/app/
      - node_modules:/app/node_modules
    networks:
      - app-network
    command: bash -c "npm run start:dev"

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
